import { defineObject, FieldType } from 'twenty-sdk/define';

import { RUSSIAN_RUBLE_DEFAULT_VALUE } from 'src/constants/currency';

export const MEMBERSHIP_OBJECT_UNIVERSAL_IDENTIFIER =
  '295ff896-3ff5-429e-b390-b52825ae03eb';
export const MEMBERSHIP_NAME_FIELD_UNIVERSAL_IDENTIFIER =
  '0a9d58bd-3f66-423c-a87c-26f13625f6da';

export default defineObject({
  universalIdentifier: MEMBERSHIP_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'studioMembership',
  namePlural: 'studioMemberships',
  labelSingular: 'Пакет клиента',
  labelPlural: 'Пакеты клиентов',
  description: 'Купленный клиентом пакет с вычисляемым остатком',
  icon: 'IconTicket',
  labelIdentifierFieldMetadataUniversalIdentifier:
    MEMBERSHIP_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: MEMBERSHIP_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Название',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: 'de3b18aa-527f-48c5-b87a-f89ef48949ca',
      type: FieldType.SELECT,
      name: 'status',
      label: 'Статус',
      icon: 'IconProgress',
      defaultValue: "'PENDING_PAYMENT'",
      options: [
        {
          id: '656033b4-183c-41e7-b32e-d9b32dc36fa4',
          value: 'PENDING_PAYMENT',
          label: 'Ожидает оплаты',
          position: 0,
          color: 'gray',
        },
        {
          id: '20ad48e3-a026-49fd-ab51-d1ae39292f53',
          value: 'ACTIVE',
          label: 'Активен',
          position: 1,
          color: 'green',
        },
        {
          id: '4586222e-b69c-41a4-a34e-85ebd14b950d',
          value: 'EXHAUSTED',
          label: 'Использован',
          position: 2,
          color: 'blue',
        },
        {
          id: '82946b5e-cee3-45b5-b6ea-76be2a8f11f1',
          value: 'EXPIRED',
          label: 'Истёк',
          position: 3,
          color: 'orange',
        },
        {
          id: '4a8d4a34-f27d-450f-8b79-545a7beae4ad',
          value: 'FROZEN',
          label: 'Заморожен',
          position: 4,
          color: 'purple',
        },
        {
          id: 'f8be0faf-eb18-4a17-a4ca-cfae924e2764',
          value: 'REFUNDED',
          label: 'Возвращён',
          position: 5,
          color: 'yellow',
        },
        {
          id: 'c8ab056f-70fa-4c31-8a16-130daf819f53',
          value: 'CANCELLED',
          label: 'Отменён',
          position: 6,
          color: 'red',
        },
      ],
    },
    {
      universalIdentifier: 'db315a46-6101-47b4-895f-52882fb02175',
      type: FieldType.DATE_TIME,
      name: 'soldAt',
      label: 'Продан',
      icon: 'IconCalendarDollar',
    },
    {
      universalIdentifier: '63b9cbd9-f0ad-4aba-8f8f-ad175ae30ff8',
      type: FieldType.DATE,
      name: 'activationDeadline',
      label: 'Активировать до',
      icon: 'IconCalendarDue',
      isNullable: true,
    },
    {
      universalIdentifier: 'c55bef89-e805-4fac-a0ed-2f79088b0838',
      type: FieldType.DATE_TIME,
      name: 'activatedAt',
      label: 'Активирован',
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    {
      universalIdentifier: '95e54120-68df-4418-a17e-62cd6e328f76',
      type: FieldType.DATE,
      name: 'expiresOn',
      label: 'Действует до',
      icon: 'IconCalendarOff',
      isNullable: true,
    },
    {
      universalIdentifier: 'b74762bc-a7dc-426d-83b6-66334d0609d3',
      type: FieldType.NUMBER,
      name: 'visitsGranted',
      label: 'Начислено',
      icon: 'IconPlus',
      defaultValue: 0,
    },
    {
      universalIdentifier: '873fd19d-b832-4c38-84e8-41d75be54477',
      type: FieldType.NUMBER,
      name: 'visitsReserved',
      label: 'Зарезервировано',
      icon: 'IconLock',
      defaultValue: 0,
    },
    {
      universalIdentifier: '82a276a4-da80-4829-af12-a6322978a11d',
      type: FieldType.NUMBER,
      name: 'visitsConsumed',
      label: 'Использовано',
      icon: 'IconCheck',
      defaultValue: 0,
    },
    {
      universalIdentifier: '6d77f594-17c4-4a95-ad8c-5b259b4bcad7',
      type: FieldType.NUMBER,
      name: 'visitsAvailable',
      label: 'Доступно',
      icon: 'IconTicket',
      defaultValue: 0,
    },
    {
      universalIdentifier: '25eb80e1-6f53-4d74-aa9f-fc6963c08647',
      type: FieldType.CURRENCY,
      name: 'purchasePrice',
      label: 'Цена покупки',
      icon: 'IconCurrencyRubel',
      defaultValue: RUSSIAN_RUBLE_DEFAULT_VALUE,
    },
    {
      universalIdentifier: '6a89bb77-10a6-4aa4-83f7-6f120bb2ee89',
      type: FieldType.CURRENCY,
      name: 'refundAmount',
      label: 'Возвращено',
      icon: 'IconCashBanknoteOff',
      isNullable: true,
      defaultValue: RUSSIAN_RUBLE_DEFAULT_VALUE,
    },
    {
      universalIdentifier: 'f4d0c4b6-3b91-45dc-95fc-c0640c55e39a',
      type: FieldType.NUMBER,
      name: 'studioExtensionDays',
      label: 'Продление, дней',
      icon: 'IconCalendarPlus',
      defaultValue: 0,
    },
    {
      universalIdentifier: '644831ad-0218-4fb9-9595-85f4124733ae',
      type: FieldType.TEXT,
      name: 'purchaseIdempotencyKey',
      label: 'Ключ покупки',
      icon: 'IconKey',
      isNullable: true,
    },
  ],
});
