---
name: twenty

services:
  server:
    image: twentycrm/twenty:${TAG}
    volumes:
      - ../../../files/server-local-data:/app/packages/twenty-server/.local-storage
    ports:
      - "3000:3000"
    networks:
      - default
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.twenty-crm.rule=Host(`crm.lan`)
      - traefik.http.routers.twenty-crm.entrypoints=web
      - traefik.http.services.twenty-crm.loadbalancer.server.port=3000
    environment:
      NODE_PORT: 3000
      # yamllint disable-line rule:line-length
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@db:5432/${PG_DATABASE_NAME}
      REDIS_URL: redis://redis:6379
      SERVER_URL: ${SERVER_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FALLBACK_ENCRYPTION_KEY: ${FALLBACK_ENCRYPTION_KEY:-}
      STORAGE_TYPE: local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  worker:
    image: twentycrm/twenty:${TAG}
    volumes:
      - ../../../files/server-local-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      # yamllint disable-line rule:line-length
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@db:5432/${PG_DATABASE_NAME}
      REDIS_URL: redis://redis:6379
      SERVER_URL: ${SERVER_URL}
      DISABLE_DB_MIGRATIONS: "true"
      DISABLE_CRON_JOBS_REGISTRATION: "true"
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FALLBACK_ENCRYPTION_KEY: ${FALLBACK_ENCRYPTION_KEY:-}
      STORAGE_TYPE: local
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    volumes:
      - ../../../files/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_DATABASE_USER}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${PG_DATABASE_USER} -d ${PG_DATABASE_NAME}
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
