import { type CSSProperties, useEffect, useState } from 'react';
import { CoreApiClient } from 'twenty-client-sdk/core';
import { RestApiClient } from 'twenty-client-sdk/rest';
import { defineFrontComponent } from 'twenty-sdk/define';
import { closeSidePanel, enqueueSnackbar, unmountFrontComponent, useSelectedRecordIds } from 'twenty-sdk/front-component';

export const MANAGE_SPLIT_BOOKING_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER = '99a8758b-dc63-4e6a-9c99-a03d2415a124';
type Context = { id: string; pair: { id: string } | null; membership: { id: string } | null; classSession: { id: string; name: string; startsAt: string; endsAt: string } | null; person: { id: string } | null; status: string };
type Result = { success: boolean; message?: string; visitsAvailable?: number };
const styles: Record<string, CSSProperties> = { container: { display: 'flex', flexDirection: 'column', height: '100%', gap: 12, padding: 16, color: 'var(--t-font-color-primary)', background: 'var(--t-background-primary)', fontFamily: 'var(--t-font-family)' }, summary: { padding: 12, background: 'var(--t-background-secondary)', border: '1px solid var(--t-border-color-light)', borderRadius: 4 }, actions: { display: 'flex', flexDirection: 'column', gap: 8 } };
const key = (): string => typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;

const ManageSplitBookingForm = () => {
  const selected = useSelectedRecordIds(); const bookingId = selected.length === 1 ? selected[0] : null;
  const [context, setContext] = useState<Context | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  useEffect(() => { if (!bookingId) return; void (async () => { try { const result = (await new CoreApiClient().query({ studioBookings: { __args: { filter: { id: { eq: bookingId } }, first: 1 }, edges: { node: { id: true, status: true, pair: { id: true }, membership: { id: true }, classSession: { id: true, name: true, startsAt: true, endsAt: true }, person: { id: true } } } } } as never)) as unknown as { studioBookings?: { edges?: Array<{ node: Context }> } }; setContext(result.studioBookings?.edges?.[0]?.node ?? null); } catch { await enqueueSnackbar({ message: 'Не удалось загрузить сплит-запись.', variant: 'error' }); } finally { setLoading(false); } })(); }, [bookingId]);
  const close = () => { unmountFrontComponent(); closeSidePanel(); };
  const perform = async (path: string, payload: object) => { if (!context?.pair || !context.membership || !context.classSession) return; setWorking(true); try { const response = await new RestApiClient().post<Result>(path, payload); if (!response.success) { await enqueueSnackbar({ message: response.message ?? 'Операция отклонена.', variant: 'error' }); return; } await enqueueSnackbar({ message: response.visitsAvailable === undefined ? 'Операция выполнена.' : `Операция выполнена. Остаток: ${response.visitsAvailable}.`, variant: 'success' }); close(); } catch (error) { await enqueueSnackbar({ message: error instanceof Error ? error.message : 'Не удалось выполнить операцию.', variant: 'error' }); } finally { setWorking(false); } };
  const base = context?.pair && context.membership && context.classSession ? { pairId: context.pair.id, membershipId: context.membership.id, classSessionId: context.classSession.id } : null;
  const session = context?.classSession;
  return <div style={styles.container}><h2>Управление сплит-записью</h2>{loading ? <div>Загрузка…</div> : !context || !base || !session ? <div style={styles.summary}>Откройте одну запись, связанную с парой, общим блоком и слотом.</div> : <><div style={styles.summary}>{session.name}<br />{new Date(session.startsAt).toLocaleString('ru-RU')}<br />Статус выбранного участника: {context.status}</div><div style={styles.actions}><button disabled={working} onClick={() => void perform('/s/studio/split-attendance/record', { ...base, idempotencyKey: `split-attendance:${session.id}` })}>Отметить пару проведённой</button><button disabled={working} onClick={() => void perform('/s/studio/split-bookings/cancel', { ...base, cancelledAt: new Date().toISOString(), idempotencyKey: key() })}>Отменить слот пары</button><button disabled={working || !context.person} onClick={() => void perform('/s/studio/split-bookings/cancel-participant', { ...base, personId: context.person?.id, cancelledAt: new Date().toISOString(), idempotencyKey: key() })}>Поздняя отмена этого участника</button></div></>}<button onClick={close} disabled={working}>Закрыть</button></div>;
};
export default defineFrontComponent({ universalIdentifier: MANAGE_SPLIT_BOOKING_FRONT_COMPONENT_UNIVERSAL_IDENTIFIER, name: 'manage-split-booking', description: 'Record attendance or cancellation for a split booking.', component: ManageSplitBookingForm });
